### ISSUE TITLE
Paste plain text.

### ISSUE THREAD

**Issue by CHEESEFIST** [alek5k/TPSyntaxHighlighter#3]
Hello Aleks. I love the TP editor. Would it be possible to allow plain text to be pasted in between  "!" and  ";" ?    I try to paste plain text and I get square shapes. Thank you.

**Comment by alek5k** [comment]
Hey there, this extension does some basic autocompletes but should not interfere with text editing in general. Are you using VS Code and did you install the extension through the extension store?

**Comment by CHEESEFIST** [comment]
Hello. Yes, I'm using VS Code and did install the extension through the extension store.


Thank you,


Michael Lepley

________________________________

**Comment by alek5k** [comment]
Seems to work for me, see gif below:

![NN5R8yWW3S](https://user-images.githubusercontent.com/20435565/106994704-6c6f6e80-67d1-11eb-8bdc-46fe22fb4bf8.gif)

Perhaps there is something wrong with your file text encoding? Or could you give me some steps to reproduce the problem?

**Comment by CHEESEFIST** [comment]
Everything is working today! I don't know what happened.


Thank you,


Michael Lepley

________________________________
